# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from brainmaze_mef3_server.protobufs import gRPCMef3Server_pb2 as brainmaze__mef3__server_dot_protobufs_dot_gRPCMef3Server__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in brainmaze_mef3_server/protobufs/gRPCMef3Server_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class gRPCMef3ServerStub:
    """MEF3 data server: every data call is oriented purely in CHANNELS and TIME.
    Open a file, inspect its metadata (channels, per-channel sampling rate and
    per-channel start/end timestamps), then read any channels over any
    [start_uutc, end_uutc) window via GetSignalRange.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.OpenFile = channel.unary_unary(
                '/gRPCMef3Server/OpenFile',
                request_serializer=brainmaze__mef3__server_dot_protobufs_dot_gRPCMef3Server__pb2.OpenFileRequest.SerializeToString,
                response_deserializer=brainmaze__mef3__server_dot_protobufs_dot_gRPCMef3Server__pb2.FileInfoResponse.FromString,
                _registered_method=True)
        self.CloseFile = channel.unary_unary(
                '/gRPCMef3Server/CloseFile',
                request_serializer=brainmaze__mef3__server_dot_protobufs_dot_gRPCMef3Server__pb2.FileInfoRequest.SerializeToString,
                response_deserializer=brainmaze__mef3__server_dot_protobufs_dot_gRPCMef3Server__pb2.FileInfoResponse.FromString,
                _registered_method=True)
        self.FileInfo = channel.unary_unary(
                '/gRPCMef3Server/FileInfo',
                request_serializer=brainmaze__mef3__server_dot_protobufs_dot_gRPCMef3Server__pb2.FileInfoRequest.SerializeToString,
                response_deserializer=brainmaze__mef3__server_dot_protobufs_dot_gRPCMef3Server__pb2.FileInfoResponse.FromString,
                _registered_method=True)
        self.GetSignalRange = channel.unary_stream(
                '/gRPCMef3Server/GetSignalRange',
                request_serializer=brainmaze__mef3__server_dot_protobufs_dot_gRPCMef3Server__pb2.SignalRangeRequest.SerializeToString,
                response_deserializer=brainmaze__mef3__server_dot_protobufs_dot_gRPCMef3Server__pb2.SignalChunk.FromString,
                _registered_method=True)
        self.ListOpenFiles = channel.unary_unary(
                '/gRPCMef3Server/ListOpenFiles',
                request_serializer=brainmaze__mef3__server_dot_protobufs_dot_gRPCMef3Server__pb2.ListOpenFilesRequest.SerializeToString,
                response_deserializer=brainmaze__mef3__server_dot_protobufs_dot_gRPCMef3Server__pb2.ListOpenFilesResponse.FromString,
                _registered_method=True)


class gRPCMef3ServerServicer:
    """MEF3 data server: every data call is oriented purely in CHANNELS and TIME.
    Open a file, inspect its metadata (channels, per-channel sampling rate and
    per-channel start/end timestamps), then read any channels over any
    [start_uutc, end_uutc) window via GetSignalRange.
    """

    def OpenFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CloseFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FileInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSignalRange(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListOpenFiles(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_gRPCMef3ServerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'OpenFile': grpc.unary_unary_rpc_method_handler(
                    servicer.OpenFile,
                    request_deserializer=brainmaze__mef3__server_dot_protobufs_dot_gRPCMef3Server__pb2.OpenFileRequest.FromString,
                    response_serializer=brainmaze__mef3__server_dot_protobufs_dot_gRPCMef3Server__pb2.FileInfoResponse.SerializeToString,
            ),
            'CloseFile': grpc.unary_unary_rpc_method_handler(
                    servicer.CloseFile,
                    request_deserializer=brainmaze__mef3__server_dot_protobufs_dot_gRPCMef3Server__pb2.FileInfoRequest.FromString,
                    response_serializer=brainmaze__mef3__server_dot_protobufs_dot_gRPCMef3Server__pb2.FileInfoResponse.SerializeToString,
            ),
            'FileInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.FileInfo,
                    request_deserializer=brainmaze__mef3__server_dot_protobufs_dot_gRPCMef3Server__pb2.FileInfoRequest.FromString,
                    response_serializer=brainmaze__mef3__server_dot_protobufs_dot_gRPCMef3Server__pb2.FileInfoResponse.SerializeToString,
            ),
            'GetSignalRange': grpc.unary_stream_rpc_method_handler(
                    servicer.GetSignalRange,
                    request_deserializer=brainmaze__mef3__server_dot_protobufs_dot_gRPCMef3Server__pb2.SignalRangeRequest.FromString,
                    response_serializer=brainmaze__mef3__server_dot_protobufs_dot_gRPCMef3Server__pb2.SignalChunk.SerializeToString,
            ),
            'ListOpenFiles': grpc.unary_unary_rpc_method_handler(
                    servicer.ListOpenFiles,
                    request_deserializer=brainmaze__mef3__server_dot_protobufs_dot_gRPCMef3Server__pb2.ListOpenFilesRequest.FromString,
                    response_serializer=brainmaze__mef3__server_dot_protobufs_dot_gRPCMef3Server__pb2.ListOpenFilesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'gRPCMef3Server', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('gRPCMef3Server', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class gRPCMef3Server:
    """MEF3 data server: every data call is oriented purely in CHANNELS and TIME.
    Open a file, inspect its metadata (channels, per-channel sampling rate and
    per-channel start/end timestamps), then read any channels over any
    [start_uutc, end_uutc) window via GetSignalRange.
    """

    @staticmethod
    def OpenFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gRPCMef3Server/OpenFile',
            brainmaze__mef3__server_dot_protobufs_dot_gRPCMef3Server__pb2.OpenFileRequest.SerializeToString,
            brainmaze__mef3__server_dot_protobufs_dot_gRPCMef3Server__pb2.FileInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CloseFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gRPCMef3Server/CloseFile',
            brainmaze__mef3__server_dot_protobufs_dot_gRPCMef3Server__pb2.FileInfoRequest.SerializeToString,
            brainmaze__mef3__server_dot_protobufs_dot_gRPCMef3Server__pb2.FileInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FileInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gRPCMef3Server/FileInfo',
            brainmaze__mef3__server_dot_protobufs_dot_gRPCMef3Server__pb2.FileInfoRequest.SerializeToString,
            brainmaze__mef3__server_dot_protobufs_dot_gRPCMef3Server__pb2.FileInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSignalRange(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/gRPCMef3Server/GetSignalRange',
            brainmaze__mef3__server_dot_protobufs_dot_gRPCMef3Server__pb2.SignalRangeRequest.SerializeToString,
            brainmaze__mef3__server_dot_protobufs_dot_gRPCMef3Server__pb2.SignalChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListOpenFiles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gRPCMef3Server/ListOpenFiles',
            brainmaze__mef3__server_dot_protobufs_dot_gRPCMef3Server__pb2.ListOpenFilesRequest.SerializeToString,
            brainmaze__mef3__server_dot_protobufs_dot_gRPCMef3Server__pb2.ListOpenFilesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
